service: startheaderinfo

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!src/**"

custom:
  includeDependencies:
    enableCaching: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: prod
  memorySize: 128
  logRetentionInDays: 1
  timeout: 10


plugins:
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

functions:
  startheaderinfo:
    handler: src/handler.run
    name: startheaderinfo
    events:
      - httpApi:
          path: /startheaderinfo
          method: get
