organization: globalhitss

service: startheaderinfo

provider:
  name: aws
  runtime: nodejs20.x
  stage: prod

plugins:
  - serverless-offline

functions:
  startheaderinfo:
    handler: handler.startheaderinfo
    events:
      - httpApi: "*"
