service: startheaderinfo

package:
  patterns:
    - "!node_modules/**" # no need to add this, this plugin does it for you

custom:
  includeDependencies:
    enableCaching: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: prod
  memorySize: 128
  logRetentionInDays: 1
  timeout: 20

plugins:
  - serverless-offline
    # disminuye el peso de la lambda cuando se deploya, no incluye los node_modules
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

functions:
  startheaderinfo:
    handler: handler.run
    name: startheaderinfo
    events:
      - httpApi:
          path: /startheaderinfo
          method: get
