organization: globalhitss

service: startheaderinfo

provider:
  name: aws
  runtime: nodejs20.x
  stage: prod
  memorySize: 128
  logRetentionInDays: 1
  timeout: 20

plugins:
  - serverless-offline

functions:
  startheaderinfo:
    handler: handler.execute
    name: startheaderinfo
    events:
      - httpApi: "*"
